### ISSUE TITLE
Queue implementation using two stacks

### ISSUE THREAD

**Issue by pratik1424** [adinimbarte/Queue#11]
I would like to add Queue implementation using two stacks in C++ language. It's commonly asked in interviews and tests one's understanding of stacks and queues. 
I'll be glad if you consider this.

**Comment by adinimbarte** [comment]
Yeah, that will be great just add it and create pull request I will merge it

**Comment by pratik1424** [comment]
I have opened a PR for the same. Waiting for your review. Thanks.
